### PR TITLE
Update README file and fixing linter style

### PR DESCRIPTION
**Pull request by melkamu12**
Updating README about key feature , Future feature and fixing style linters problem

### CODE REVIEW

**Review by ademibowale — COMMENTED** [review]
Hi @melkamu12 e,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project with a wrong PR please kindly submit a project of the previous review untill its approve , , please use this [Template](https://github.com/microverseinc/readme-template/blob/master/README.md) to create a professional documentation

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by melkamu12** [comment]
how are you?

What is the problem dear brother? please put it clearly

**Comment by ademibowale** [comment]
on this particular project one reviewer have reviewed it  and requested for a changes so while done with the changes you have to submit the same pull reqest for second review untill its approved
is that clear pls

**Comment by melkamu12** [comment]
Would you help me to do that, dear brother? just let us talk with video
call in Zoom

**Comment by ademibowale** [comment]
no i am not available rightnow on zoom nut its easy just switch back to the branch where you created the first pull request for last review and follow up the changes requested from the reviewer  implement all the changes and then commit all ur changes and finally dont create a new pull create just submit the pull request from the same branch

**Pull request closed without merging**
